id: 86f2f26b0bd146eb833dd23acdcfce86
initial_creation_type: ocr
source_metadata:
  volumes:
    45c858ceb9d845eba305279f784d8d47:
      base_file: v060.txt
      image_group_id: I1PD95906
      title: ''
      total_pages: 1877
      volume_number: 61
